name: Feishu Webhook Notification

on:
  workflow_dispatch:
  schedule:
    - cron: '50 7 * * *'

jobs:
  send_notification:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.10", "3.11", "3.12"]

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run webhook script
      env:
        WEBHOOK_URL: ${{ secrets.WEBHOOK_URL }}
        USER_ID: ${{ secrets.USER_ID }}
      run: |
        python feishu_notifier.py
